import os
import json
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(PROJECT_ROOT, "data", "qr_dataset.csv")
SELF_TRAINING_FILE = os.path.join(PROJECT_ROOT, "data", "high_risk_samples.csv")
MODEL_DIR = os.path.join(PROJECT_ROOT, "model")
MODEL_FILE = os.path.join(MODEL_DIR, "qr_model.pkl")
FEATURE_FILE = os.path.join(MODEL_DIR, "feature_names.pkl")
METRICS_FILE = os.path.join(MODEL_DIR, "training_metrics.json")


def train_model():
    """
    Train a NEW Random Forest model from the project's dataset.

    This function does not use a pre-trained model. Every time it is called,
    a fresh RandomForestClassifier is created and fitted on the training split.
    The trained model is then saved locally only for later predictions.
    """
    print("\n======================================")
    print("      QR SHIELD ML MODEL TRAINING")
    print("======================================\n")

    if not os.path.exists(DATA_FILE):
        raise FileNotFoundError(
            f"Dataset file {DATA_FILE} not found. Run prepare_dataset.py first."
        )

    df = pd.read_csv(DATA_FILE)
    base_rows = len(df)

    # Add only the high-risk samples collected automatically since the last
    # training cycle. The original project dataset is never modified.
    if os.path.exists(SELF_TRAINING_FILE):
        extra = pd.read_csv(SELF_TRAINING_FILE)
        if not extra.empty and {"data", "label"}.issubset(extra.columns):
            from utils.feature_extraction import extract_features
            extra_rows = []
            for _, row in extra.drop_duplicates(subset=["data"]).iterrows():
                features = extract_features(str(row["data"]))
                features["Label"] = int(row["label"])
                extra_rows.append(features)
            if extra_rows:
                df = pd.concat([df, pd.DataFrame(extra_rows)], ignore_index=True)

    print(f"Base dataset rows: {base_rows}")
    print(f"Total training dataset rows: {df.shape[0]} (including auto-collected samples if any).")

    if "Label" not in df.columns:
        raise ValueError("Label column missing from dataset!")

    X = df.drop(columns=["Label"])
    y = df["Label"]

    if y.nunique() < 2:
        raise ValueError("Dataset must contain at least two classes in Label.")

    feature_names = list(X.columns)
    print(f"Total Extracted Features: {len(feature_names)}")

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
        stratify=y
    )

    print(f"Train set size: {len(X_train)} | Test set size: {len(X_test)}")

    # Fresh, project-owned Random Forest classifier.
    model = RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1
    )

    print("\nTraining a fresh Random Forest Classifier...")
    model.fit(X_train, y_train)
    print("Training complete.")

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_accuracy = accuracy_score(y_train, train_pred)
    test_accuracy = accuracy_score(y_test, test_pred)
    report = classification_report(
        y_test, test_pred, output_dict=True, zero_division=0
    )
    matrix = confusion_matrix(y_test, test_pred).tolist()

    print("\n======================================")
    print("          MODEL EVALUATION")
    print("======================================")
    print(f"Training Accuracy: {train_accuracy * 100:.2f}%")
    print(f"Test Accuracy:     {test_accuracy * 100:.2f}%")
    print("\nClassification Report:")
    print(classification_report(y_test, test_pred, zero_division=0))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, test_pred))

    os.makedirs(MODEL_DIR, exist_ok=True)

    # These files are generated by THIS project's training code.
    joblib.dump(model, MODEL_FILE)
    joblib.dump(feature_names, FEATURE_FILE)

    metrics = {
        "algorithm": "Random Forest Classifier",
        "n_estimators": 300,
        "max_depth": 12,
        "class_weight": "balanced",
        "dataset_rows": int(len(df)),
        "feature_count": int(len(feature_names)),
        "train_rows": int(len(X_train)),
        "test_rows": int(len(X_test)),
        "training_accuracy": float(train_accuracy),
        "test_accuracy": float(test_accuracy),
        "confusion_matrix": matrix,
        "classification_report": report,
        "trained_from_dataset": DATA_FILE,
        "base_dataset_rows": int(base_rows),
        "auto_collected_high_risk_samples": int(len(df) - base_rows),
    }
    with open(METRICS_FILE, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    print(f"\nFresh trained model saved to: {MODEL_FILE}")
    print(f"Feature list saved to: {FEATURE_FILE}")
    print(f"Training metrics saved to: {METRICS_FILE}")
    print("======================================\n")

    return metrics


if __name__ == "__main__":
    train_model()
